export interface EatUp {
  _id: string; // Automatically generated by MongoDB
  authorId: string; // New field for the author's ID
  zone: "North" | "South" | "Center"; // Enum type for the zone
  title: string; // Required
  owner: string; // Required
  date: string; // ISO date string, required
  kosher: boolean; // Required
  description?: string; // Optional
  language: string; // Required
  hosting?: string; // Optional
  religios?: boolean; // Optional
  media?: string[];  // Add this line
  phone?: string;    // Add this line
}
